substitutions:
  tx_pin: "17"
  rx_pin: "16"
  re_de_pin: "21"
  comfortzone_protocol_version: "170"
  device_name: "Comfortzone_"
  git_branch: "fix/api-service-crash-guard"
  git_commit_hash: "34ae639b6557c30ab549c7fbfadf79d17748cb77"

packages:
  comfortzone_package: github://pinussen/esphome-comfortzone/comfortzone-package.yaml@fix/api-service-crash-guard

esphome:
  name: comfortzone
  platformio_options:
    build_flags:
      - -DUSE_ESPHOME
  on_boot:
    priority: 800
    then:
      - lambda: |-
          esp_log_level_set("comfortzone", ESP_LOG_DEBUG);

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:
  level: DEBUG
  logs:
    comfortzone: DEBUG

api:
  encryption:
    key: !secret api_key
  custom_services: true

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    continuous: true

sensor:
  - platform: inkbird_ibsth1_mini
    mac_address: 49:22:01:23:02:BD
    temperature:
      name: "Inkbird Vaexthus Temperature"
      filters:
        - throttle: 60s
    humidity:
      name: "Inkbird Vaexthus Humidity"
      filters:
        - throttle: 60s
    battery_level:
      name: "Inkbird Vaexthus Battery Level"
      filters:
        - throttle: 60s
  - platform: inkbird_ibsth1_mini
    mac_address: 49:22:01:23:09:4D
    temperature:
      name: "Inkbird overvaning Temperature"
      filters:
        - throttle: 60s
    humidity:
      name: "Inkbird overvaning Humidity"
      filters:
        - throttle: 60s
    battery_level:
      name: "Inkbird overvaning Battery Level"
      filters:
        - throttle: 60s
  - platform: inkbird_ibsth1_mini
    mac_address: 49:22:01:23:07:BA
    temperature:
      name: "Inkbird utomhus Temperature"
      filters:
        - throttle: 60s
    humidity:
      name: "Inkbird utomhus Humidity"
      filters:
        - throttle: 60s
    battery_level:
      name: "Inkbird utomhus Battery Level"
      filters:
        - throttle: 60s